#  Copyright (c) 2026 finance-dag Contributors
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  or implied. See the License for the specific language governing
#  permissions and limitations under the License.

from __future__ import annotations

class Node:
    """
    A C-level extension type representing a single node in the DAG.
    """

    def add_dependency(self, dep: Node) -> None:
        """Creates a bidirectional edge. Prevents duplicates during dynamic access."""

    def invalidate(self) -> None:
        """
        Fast C-level recursive invalidation.
        Uses bint (boolean integer) for 0-overhead checks.
        """

    def __init__(
        self, name: str, func: object, is_explicit: bool = False, explicit_value: object = None, flags: int = 0
    ): ...

class DAGEngine:
    """Manages the lifecycle and topology of the graph."""

    def add_node(
        self, name: str, func: object, is_explicit: bool = False, explicit_value: object = None, flags: int = 0
    ) -> Node: ...
    def add_edge(self, dependent_name: str, dependency_name: str) -> None: ...
    def record_access(self, accessed_node_name: str) -> None: ...
    def invalidate(self, name: str) -> None: ...
    def evaluate(self, name: str, instance: object) -> object: ...
    def __init__(self): ...

# This file was generated by stubgen-pyx v0.2.4 from fdag\fast_dag.pyx
